server:
  port: 8182

logging:
  level:
    com.food.ordering.system: DEBUG

spring:
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql